### ISSUE TITLE
node 12 is deprecated

### ISSUE THREAD

**Issue by amitdo** [egorpugin/sw-action#5]
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

We get warnings about this in sw jobs in Tesseract.

**Comment by egorpugin** [comment]
Could you provide a link to those warnings?

Not sure where it is.
https://github.com/tesseract-ocr/tesseract/actions/runs/3312638685/jobs/5469559558

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/actions/runs/3309148654

<h4 class="text-bold">Annotations</h4>
<div class="color-fg-muted text-small">6 warnings</div>
